# Generated by Django 3.2.25 on 2025-02-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_id', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.IntegerField()),
                ('duration', models.FloatField()),
                ('text', models.TextField()),
                ('embedding', models.JSONField()),
            ],
        ),
    ]
